name: 'foundry_quality'
version: '1.0.0'
config-version: 2

profile: 'foundry_quality'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  foundry_quality:
    staging:
      +materialized: view
    marts:
      +materialized: table
